version: '3'

volumes:
  pg-data:

networks:
  backend:

services:
  postgres:
    container_name: eth-scan
    image: postgres:14
    env_file:
      - .env
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    restart: always
    networks:
      backend:
